### ISSUE TITLE
关于替换了assets 下path_dex.jar 后无法修复的问题

### ISSUE THREAD

**Issue by xiangou** [dodola/HotFix#10]
如题
步骤如下 1 我将bugClass   中的 bug 方法返回值进行修改
                  2 将他拷贝到D:\HotFixPack 下
                  3 jar cvf path.jar d:\HotFixPack\BugClass.java  或得到 path.jar 文件
                   4 通过 DX  打包获得到 path_dex.jar   
                    5 替换   点击修复  -----  点击测试  没有改变返回值
我所有的步骤都在上述的操作中

**Comment by xiangou** [comment]
我是否少了什么步骤 谢谢

**Comment by mox113** [comment]
同...  有条log  dodola.hotfix E/dalvikvm: Unable to extract+optimize DEX from '/data/data/dodola.hotfix/app_dex/path_dex.jar'   他说没有加载进来？     大神（作者）帮看看呗

**Comment by mox113** [comment]
刚弄好了   jar cvf path.jar d:\HotFixPack\BugClass.java   这个  这样打jar包有的时候貌似有问题  我是用eclipse 把BugClass.java 打成一个jar 然后用dx转成dex 的jar  现在可以了

**Comment by xiangou** [comment]
恩 但是楼主说 这个项目停止更新，他提议用NAWA，NAMW 还一直配不成功....

**Comment by mox113** [comment]
我的namw就打不开... 等等再看看这个  熟悉了之后  直接把namw转成eclipse的项目看看能用不

**Comment by xiangou** [comment]
恩好的稍后再去弄 下刚那个问题 ，还有就是 尽快转 Studio吧

**Comment by mox113** [comment]
平时是两个混用 我的死丢丢打不开nuwa 等等看看是不是sdk的问题

**Comment by xiangou** [comment]
哈哈 死丢丢 看下可能是GRADLE  版本是否正确  编译版本是否有

**Comment by dodola** [comment]
fixed in [RocooFix](https://github.com/dodola/RocooFix)
