### ISSUE TITLE
使用gradle2.1.0 build失败

### ISSUE THREAD

**Issue by ouyang1738** [dodola/HotFix#15]
Error:(32, 0) Access to the dex task is now impossible, starting with 1.4.0
1.4.0 introduces a new Transform API allowing manipulation of the .class files.
See more information: http://tools.android.com/tech-docs/new-build-system/transform-api

**Comment by dodola** [comment]
@ouyang1738 请看这个项目[RocooFix](https://github.com/dodola/RocooFix)
