### ISSUE TITLE
Demo工程hotfix不生效.

### ISSUE THREAD

**Issue by Eklett** [dodola/HotFix#2]
我用2台手机测试Demo,一台魅蓝note2 系统flyme4.5.4, android版本5.1; 另一台一加1 系统color os,Android版本4.4........
demo 编译成功后,
①如果先点击"测试",之后打补丁重启应用之后也不生效;
②如果先点击"打补丁",之后点击"测试",
魅蓝的不用重启补丁立即生效了.
一加的就会crash
日志:

```java
Class resolved by unexpected DEX: Ldodola/hotfix/LoadBugClass;(0x42706028):0x719cf000 ref [Ldodola/hotfix/BugClass;] Ldodola/hotfix/BugClass;(0x42706028):0x7ac15000
(Ldodola/hotfix/LoadBugClass; had used a different Ldodola/hotfix/BugClass; during pre-verification)
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    at dodola.hotfix.LoadBugClass.getBugString(LoadBugClass.java:11)
    at dodola.hotfix.MainActivity.onOptionsItemSelected(MainActivity.java:72)
    at android.app.Activity.onMenuItemSelected(Activity.java:2655)
```

**Comment by dodola** [comment]
@Eklett 有些厂家可能改了libdvm，造成这种方法失效。等我找个手机查查。。

**Comment by Eklett** [comment]
反编译进去app-debug.apk看,没有发现构造方法 , 所以也没有System.out.println(dodola.hackdex.AntilazyLoad.class);这句....难道是Groovy SDK配置不成功?

**Comment by jasonross** [comment]
@Eklett  https://github.com/jasonross/Nuwa 帮忙看一下这个项目成功不？

**Comment by Eklett** [comment]
正在看,没找到生成的patch.jar..

**Comment by Eklett** [comment]
女娲是可以成功的.

**Comment by dodola** [comment]
@Eklett 女娲😂 赞一个

**Comment by dodola** [comment]
@jasonross 被你截胡了，桑心

**Comment by jasonross** [comment]
@dodola  哈哈，但是为什么我还没上trending？

**Comment by dodola** [comment]
@jasonross 可能还没到刷新缓存的时候

**Comment by dodola** [comment]
fixed in [RocooFix](https://github.com/dodola/RocooFix)
