### ISSUE TITLE
如果相应的类被混淆了怎么处理？

### ISSUE THREAD

**Issue by terryyhl** [dodola/HotFix#4]

**Comment by dodola** [comment]
@terryyhl 哈，这部分还没写，但是逻辑上比较简单。
文档里已经给出了解决方案。
１. 在正式版本发布的时候，会生成一份缓存文件，里面记录了所有class文件的md5，还有一份mapping混淆文件。２. 在后续的版本中使用-applymapping选项，应用正式版本的mapping文件，然后计算编译完成后的class文件的md5和正式版本进行比较，把不相同的class文件打包成补丁包。
就是从有补丁功能的版本开始，保存一份mapping混淆文件，后续编译用同一个混淆mapping文件，这样就能保证混淆过后的类名始终是一致的。
这样打补丁混淆就能完全的自动化了。

**Comment by jasonross** [comment]
@terryyhl  https://github.com/jasonross/Nuwa已经把混淆做了

**Comment by dodola** [comment]
fixed in [RocooFix](https://github.com/dodola/RocooFix)
